### ISSUE TITLE
Task-3 The Splash Screen

### ISSUE THREAD

**Issue by aarav0180** [opencodeiiita/CodeBuddy#3]
🚀 Create a Splash Screen with Transition to NextActivity

Hey everyone!
Your task is to develop a splash screen that:
1️⃣ Dynamically engages users for 3 seconds.
2️⃣ Seamlessly transitions to the NextActivity (or next screen).

What we’re looking for:
A visually appealing and modern design for the splash screen to capture user attention. 🎨
Smooth transition animations for a better user experience.
Additional Info:
This issue is not open for everyone— you need to claim it. Comment to claim the issue.
Deadline: The issue will be active for 3 days ⏳.
We’re excited to see your designs come to life. Let’s make this app’s first impression unforgettable! 🚀

Happy contributing! 😊

**Comment by Navigam1108** [comment]
claim

**Comment by aarav0180** [comment]
Sure! The task has been assigned to @Navigam1108 . 🎉

You have 2 days to complete it. Feel free to reach out to me if you need any help or clarification. 😊

Good luck! 🚀
