### ISSUE TITLE
Task-4 🔐 Build a Beautiful Login Experience: Phone

### ISSUE THREAD

**Issue by aarav0180** [opencodeiiita/CodeBuddy#41]
**📱 Implement Phone Login and Signup with OTP Using Firebase**

Your task is to implement **Phone Number Authentication with OTP** using Firebase, enabling users to **log in** or **sign up** securely via their phone numbers.

### **Requirements**

- **Login Flow**  
  1. Create a **Phone Login Screen** with:  
     - A field to input the **phone number**.  
     - A button to **send the OTP**.  
     - A field to input the **OTP received**.  
     - A button to **verify the OTP** and log the user in.  
  2. Use **Firebase Authentication** to:  
     - Send the OTP to the entered phone number.  
     - Verify the OTP upon user input.  
     - Log in the user upon successful verification.  

- **Signup Flow**  
  1. Allow users to **sign up** with their phone number by:  
     - Prompting for their **name** and **phone number** during signup.  
     - Sending and verifying an OTP to confirm their phone number.  
     - Storing additional user details (e.g., name) in Firebase Firestore after successful verification.  
  2. After signup, the user should be redirected to the app's home screen, with their data saved for future sessions.  

- **General Requirements**  
  - **Error Handling**:  
    - Display errors for invalid phone numbers, incorrect OTP, or Firebase-related issues.  
    - Show messages like “OTP sent!” or “Verification failed!” for better user feedback.  
  - **Resend OTP**:  
    - Add a "Resend OTP" button with a cooldown timer (e.g., 30 seconds).  

### 💡 **Bonus**
- Include animations for a smoother user experience.  
- Validate the **name field** during signup (e.g., no empty names).  

Let’s build a seamless and secure **login and signup** process for our app! 🚀  

**Please note that this is a first come first serve issue, comment to claim to do the task and the deadline is 3 days.**

For design inspirations, you can take inspiration from below 

https://www.figma.com/design/8jtHChpXCMSqrK5RJdo9Hq/Memo-Mobile-(Community)-(Community)?node-id=29-1156&t=MNqLh7jchtPNIocF-1

![Screenshot 2024-12-16 235827](https://github.com/user-attachments/assets/df9beb8e-80b1-4cb4-838e-fa5a78a07e2d)
![WhatsApp Image 2024-12-17 at 12 00 12 AM](https://github.com/user-attachments/assets/c466d202-8bea-47c4-88f7-210e87d9c30e)

**Comment by puravimohta15** [comment]
claim

**Comment by aarav0180** [comment]
Sure! The task has been assigned to @puravimohta15 . 🎉

You have 3 days to complete it. Feel free to reach out to me if you need any help or clarification. 😊

Good luck! 🚀

**Comment by aarav0180** [comment]
🚨 Issue Available to Claim! 🚨

Hey everyone! 👋 The issue has been unassigned and is now available again! 💥 If you’re interested in taking it on, just comment below to claim. First come, first served—grab it while you can! 🙌

Let’s keep building! 🚀

**Comment by kanav67** [comment]
claim

**Comment by aarav0180** [comment]
Sure! The task has been assigned to @HGRgamer  . 🎉

You have 2 days to complete it. Feel free to reach out to me if you need any help or clarification. 😊

Good luck! 🚀

**Comment by Aditya-602** [comment]
claim

**Comment by aarav0180** [comment]
/details

/details

</p>
</details>

**Comment by aarav0180** [comment]
Hey @HGRgamer! 👋

Just checking in—how’s the progress on the task going? 😊 Let me know if you’re facing any challenges or need any help. 💪 We’re excited to see your work! 🚀

Looking forward to your update! 🙌
