### ISSUE TITLE
Task-5 Home Screen Magic ✨🏠

### ISSUE THREAD

**Issue by aarav0180** [opencodeiiita/CodeBuddy#42]
🏠 **Design a Home Screen with Three Functional Sections and Bottom Navigation Bar**

Your task is to design and implement a Home Screen that contains three distinct sections to enhance user engagement and functionality, along with a **Bottom Navigation Bar** for easy navigation.

#### **1. Question of the Day Section**
- Display the **Question of the Day** prominently at the top of the screen.
- Include:
  - **Question title**.
  - A short **description** or **tag** (e.g., category, difficulty).
  - A button or link to **View Details** or **Solve Now**.

#### **2. Difficulty Selection Section**
- Below the Question of the Day, create a section for **Difficulty Selection**:
  - Allow users to select a **difficulty level** (e.g., Easy, Medium, Hard).
  - Based on the selected difficulty, display a **problem title** and a short **description**.
  - Add a button to **Solve Problem** or **View Details** for the selected difficulty.

#### **3. Random Problems Section**
- At the bottom, add a section for **Random Problems**:
  - Display a **scrollable list** or **grid** of random problems.
  - Each problem card should show:
    - **Problem title**.
    - **Tags** or **difficulty level**.
    - A button to **Solve Now** or **View Details**.

### **Design Guidelines**
- Ensure the layout is **responsive** and looks good across different screen sizes.
- Use **consistent fonts, colors, and spacing** to match the app’s theme.
- Add **subtle animations** or transitions for an enhanced user experience.

### 💡 **Bonus**
- Add **icons or images** to make each section visually engaging.
- Include a **progress tracker** for solved problems within the sections.
- Show a **loading animation** or **placeholder** when problems are being fetched.

---

### **Bottom Navigation Bar**

To enhance the user experience, include a **Bottom Navigation Bar** with the following tabs:

- **Home**: Takes the user to the main screen where they can view the sections.
- **Search**: Allows users to search for problems based on tags or difficulty.
- **Profile**: Shows the user's progress, statistics, and settings.
- **Settings**: Provides access to app settings and preferences.

**Design Considerations for Bottom Navigation Bar**:
- Ensure the bottom navigation bar is **fixed** at the bottom of the screen and is always accessible.
- The icons should be clear and easy to understand, with a focus on user experience.
- Use **active state** indicators to show the current tab selection.

---

**This is a competitive issue so just try your best designs and submit the code with a screenshot of your design. The best PR will be merged into the main repo.**

Let’s build a Home Screen that’s both **functional** and **visually appealing** with easy navigation to keep users engaged! 🚀

**For design inspirations and color palettes of the app**
[See this Figma file](https://www.figma.com/design/8jtHChpXCMSqrK5RJdo9Hq/Memo-Mobile-(Community)-(Community)?node-id=29-1156&t=MNqLh7jchtPNIocF-1)

**Comment by ashutosh-iiita0** [comment]
Claim

**Comment by official-ashutosh** [comment]
Claim

**Comment by muffinboy19** [comment]
claim

**Comment by aarav0180** [comment]
🚨 Competitive Issue Announcement! 🚨

Hey everyone! 👋 This is a competitive issue, so there’s no need to claim it! 🏆 Just work on the task, submit your PR, and give it your best shot. 💪

The best PR will be selected and merged, so focus on quality and creativity!

Good luck! 🚀🔥
