### ISSUE TITLE
Task-6 🔍✨ Find It Fast!

### ISSUE THREAD

**Issue by aarav0180** [opencodeiiita/CodeBuddy#55]
### **✨ Description ✨**  
 
Hey, code wizards! 🧙‍♂️✨ Your mission is to design and build a **Search Screen** that’s smooth, functional, and a joy to use! 🎯 Here’s what you need to do:  

1️⃣ **Search Bar Magic**:  
   - Add a sleek search bar at the top where users can type their questions.  
   - Placeholder idea: "What are you curious about today?" 🤔  

2️⃣ **API Superpowers**:  
   - Integrate the API to fetch search results.  
   - Show a loading animation while results load 🌀 and handle errors gracefully (e.g., "No questions found" or "Oops, something went wrong").  

3️⃣ **Result Showcase**:  
   - Use a **ListView** to display search results in style!  
   - Each list item should include:  
     - Question title.  
     - A short description or tag.  
     - Any other relevant info from the API.  

### **🎯 Bonus XP:**  
- Add fancy animations for results appearing on the list 🎥.     

💡 **Pro Tip**: Think user-friendly and visually appealing. Let’s make searching a breeze! 🌈 Ready to make magic? Let’s go! 🔥

###**For API :**
** You can see here, [Problems](https://alfa-leetcode-api.onrender.com/problems?tags=array+math).**
Method is GET and in tags just change the string.

### **Comment to claim the issue.**

see this Figma file for color palette: https://www.figma.com/design/8jtHChpXCMSqrK5RJdo9Hq/Memo-Mobile-(Community)-(Community)?node-id=29-1157&t=Tq5oBc4Gk3x30kFg-1 

**Good luck for the issue. Ping me on Discord if you any doubts.**

**Comment by aarav0180** [comment]
Sure! The task has been assigned to @Debankur04 . 🎉

You have 2 days to complete it. Feel free to reach out to me if you need any help or clarification. 😊

Good luck! 🚀

**Comment by aarav0180** [comment]
🚨 Issue Available to Claim! 🚨

Hey everyone! 👋 The issue has been unassigned and is now available again! 💥 If you’re interested in taking it on, just comment below to claim. First come, first served—grab it while you can! 🙌

Let’s keep building! 🚀 

You can comment now to claim the issue.

**Comment by official-ashutosh** [comment]
Claim

**Comment by Navigam1108** [comment]
Claim

**Comment by aarav0180** [comment]
The task has been assigned to @official-ashutosh. 🎉

You have 2 days to complete it. Feel free to reach out to me if you need any help or clarification. 😊

Good luck! 🚀
