### ISSUE TITLE
Task - 8 🎭 Unveil the Magic: Design the Profile Page of the Future!

### ISSUE THREAD

**Issue by aarav0180** [opencodeiiita/CodeBuddy#59]
#### **Description**  
Are you ready to design a profile page that’s not just functional but downright irresistible? 🌟 Let’s build a next-level experience that showcases user achievements in style—coded entirely in **Flutter**!  

Here’s your checklist for awesomeness:  
1. 📊 **LeetCode Progress Graphs**: Create sleek, interactive graphs to show off problem-solving trends (e.g., problems solved over time, categories mastered).  
2. 🧮 **Problem-Solving Stats**: Highlight key stats like total problems solved, streaks, and recent activity for that extra wow factor.  
3. 🏅 **Achievements Section**: Add a dash of gamification with badges, milestones, or cool rewards to celebrate success.  
4. 🎨 **Personalized Design**: Keep it modern, clean, and customizable with options like themes or visibility settings.  
5. 📱 **Mobile-First Magic**: Ensure the design is responsive and buttery smooth across devices.  

#### **Submission Guidelines**  
- 🛠️ Code the **entire profile page in Flutter**.  
- 📸 Include a **screenshot** of your masterpiece in the PR description.  
- ✨ Ensure the code is clean, well-documented, and ready for production.  

#### **Claiming the Issue**  
⚡ **Drop a comment below to claim this issue before starting.** First come, first served—don’t miss your chance to shine! 🌟  

see this Figma file for color palette: https://www.figma.com/design/8jtHChpXCMSqrK5RJdo9Hq/Memo-Mobile-(Community)-(Community)?node-id=29-1157&t=Tq5oBc4Gk3x30kFg-1 

**Good luck for the issue. Ping me on Discord if you any doubts.**

Let’s create a profile page that users can’t wait to flaunt. Ready to make magic happen? Bring it on! 💪🚀

**Comment by kanav67** [comment]
claim

**Comment by aarav0180** [comment]
@HGRgamer Wait.. the claiming will start from 12

**Comment by PriyamJChakrabarty** [comment]
Claim

**Comment by aarav0180** [comment]
🚨 **Important Update:** As mentioned earlier, claiming will kick off at **12:00 PM** ⏰. 
The first claim after 12:00 has been assigned to @SHARUKA-2005🏅. 

Please ensure to complete the task within the next **2 days** 🗓️, by **22nd EOD.**.

If you have any questions or need more info, don’t hesitate to reach out! 💬

**Comment by official-ashutosh** [comment]
claim

**Comment by aarav0180** [comment]
Hey @SHARUKA-2005! 👋

Just wanted to check in—how’s the progress on your assigned issue? 🚀
If you need any help or have questions, feel free to ping me.💻✨

**Comment by SHARUKA-2005** [comment]
Can't make it within today, you can assign someone..

**Comment by aarav0180** [comment]
Hey @SHARUKA-2005!,

No worries about the task—it’s okay to step back sometimes! 💙 You gave it your best, and that matters. Don’t be discouraged; every effort helps you grow! 💪 I’m sure you’ll crush it next time.

You’ve got this! 🚀

**Comment by aarav0180** [comment]
🚨 Issue Available to Claim! 🚨

Hey everyone! 👋 The issue has been unassigned and is now available again! 💥 If you’re interested in taking it on, just comment below to claim. First come, first served—grab it while you can! 🙌

Let’s keep building! 🚀

**Comment by PriyamJChakrabarty** [comment]
Claim

**Comment by kanav67** [comment]
claim

**Comment by aarav0180** [comment]
Sure! The task has been assigned to @PriyamJChakrabarty. 🎉

You have 2 days to complete it. Feel free to reach out to me if you need any help or clarification. 😊

Good luck! 🚀

**Comment by official-ashutosh** [comment]
I claimed this project before @PriyamJChakrabarty then how can u assign this to him ?

**Comment by aarav0180** [comment]
@official-ashutosh It's been unassigned today and I'm seeing the claims after unassigning the task.

**Comment by aarav0180** [comment]
Hey @PriyamJChakrabarty ! 👋

Just wanted to check in—how’s the progress on your assigned issue? 🚀
If you need any help or have questions, feel free to ping me.💻✨

**Comment by PriyamJChakrabarty** [comment]
@aarav0180 man u assigned me recently😅.....will update you tmrw

**Comment by aarav0180** [comment]
Haha, no worries @PriyamJChakrabarty ! 😅
Take your time—looking forward to seeing your update tomorrow! 🚀
Let’s crush it! 💪🔥
