### ISSUE TITLE
Task-11 🚀 Bring It to Life🌟

### ISSUE THREAD

**Issue by aarav0180** [opencodeiiita/CodeBuddy#68]
### **🔗 Task 11: Description! 🌐**  

Hey tech wizards! 🧙‍♂️✨ Your mission for this task is to integrate APIs into the **Home Screen** to make it fully functional and dynamic. Let’s connect the UI to the backend and watch the magic happen! 🚀  

---

### **🎯 What You Need to Do:**  
1️⃣ Integrate the **Question of the Day API** to display a dynamic question on the home screen.  
2️⃣ Use the **Difficulty Selection API** to fetch and display problems based on the selected difficulty (Easy, Medium, Hard).  
3️⃣ Connect the **Random Problems API** to populate the random problems section with engaging content.  

---

### **Requirements:**  
- Ensure proper **error handling** for scenarios like failed API calls or no data.  
- Add **loading indicators** for a smooth user experience while fetching data.  
- Test all integrations thoroughly to ensure seamless functionality.  

---

### **💡 Bonus:**  
- Optimize API calls for better performance.  
- Use animations to enhance the transitions between loading and loaded states.  

Let’s make the Home Screen dynamic and interactive! 🌟 Ready to show your backend integration skills? 🚀  

---

### **💬 COMMENT TO CLAIM THIS TASK!**  

**APIs to Integrate in the Home Screen:**  
1. **[Question of the Day API](https://alfa-leetcode-api.onrender.com/daily)**  
2. **Difficulty-Based Problem API** **This will be given later**  
3. **[Random Problems API](https://alfa-leetcode-api.onrender.com/problems)** 

Let’s get started! 🚀

**Comment by kanav67** [comment]
claim

**Comment by official-ashutosh** [comment]
claim

**Comment by kanav67** [comment]
@aarav0180 whats the status of this ?

**Comment by aarav0180** [comment]
@PriyamJChakrabarty is working on it rn. 
If it's not completed then I will inform you here.

**Comment by aarav0180** [comment]
**Hey @PriyamJChakrabarty! 👋**  

Just a quick heads-up—it's been 2 days since the issue was assigned, and I haven’t seen any updates yet. ⏳ To keep things moving, I’ll be unassigning it for now.  

No worries, though—feel free to reassign yourself or grab a new issue whenever you're ready! 💪✨  

Thanks for understanding! 🚀😊

**Comment by aarav0180** [comment]
📢 **Attention Team! 🚀**  

The issue **"Task-11 🚀 Bring It to Life🌟"** has been unassigned and is now **ready to claim!** 🎉  

⚡ **Claiming opens at 12:00 AM sharp**, so get your keyboards ready and grab the chance to showcase your skills! First come, first served—don’t miss out! ⏳  

💬 Have questions? Drop them in the chat—we’re here to help!  

Good luck, coders! 💻✨

**Comment by official-ashutosh** [comment]
Claim

**Comment by PriyamJChakrabarty** [comment]
Claim

**Comment by YASMIN-SEKH** [comment]
claim

**Comment by aarav0180** [comment]
Task assigned to @official-ashutosh, you have 2 days to finish the task.
