### ISSUE TITLE
Task 14: 🛠️✨ Crack the Code: Bring LeetCode Stats to Life! 🚀

### ISSUE THREAD

**Issue by aarav0180** [opencodeiiita/CodeBuddy#77]
**🚀 Description:**  

Let’s level up the user experience with this exciting feature! Here’s what you’ll do:  
1️⃣ **Interactive Dialog:** Create a sleek dialog box to capture the user’s LeetCode username.  
2️⃣ **Local Storage Magic:** Save the input securely in the local cache for instant retrieval.  
3️⃣ **API Integration:** Use the stored username to fetch stats from the LeetCode API and display them dynamically in the app.  

**🎯 Why this matters?**  
This feature brings personalization to life, letting users track their coding journey seamlessly. It’s fast, it’s functional, and it’s fun! 🚀  

**This has to be done in profile page.**

### **COMMENT TO CLAIM THE ISSUE!**

Let’s make this happen! 🌟

**Comment by official-ashutosh** [comment]
Claim

**Comment by aarav0180** [comment]
@official-ashutosh claiming starts from 12

**Comment by PriyamJChakrabarty** [comment]
Claim

**Comment by official-ashutosh** [comment]
Claim

**Comment by YASMIN-SEKH** [comment]
claim

**Comment by aarav0180** [comment]
Issue assigned to @PriyamJChakrabarty for the first comment after 12.

**Comment by Nirmit2103** [comment]
Claim
